Fix/wordpress action
saritasa-nest/saritasa-github-actions pull request #12
Opened 2024-10-31 07:04 UTC by udaltsovra

### Summary

Task: [SD-???](https://saritasa.atlassian.net/browse/SD-???)

![image](https://github.com/user-attachments/assets/03f8e0b1-688b-49dc-ab92-771a034005ea)

2024-10-31 08:04 UTC, roman-mightydevops requested changes

2024-10-31 08:04 UTC, roman-mightydevops commented on .github/workflows/ci-wordpress-rollback.yaml
> +          pip install ansible-core==2.16.6 requests jinja2
Let's parameterize ansible version, instead of hardcoding

2024-10-31 13:53 UTC, roman-mightydevops approved these changes

2024-10-31 20:03 UTC, DanilaKazakevich approved these changes

2024-10-31 22:08 UTC, dmitry-mightydevops approved these changes

2024-11-01 04:44 UTC, darliiin approved these changes

2024-11-01 05:31 UTC, KrawczowaKris approved these changes

2024-11-01 05:52 UTC, MikhailKorol-saritasa approved these changes

2024-11-01 09:25 UTC, merged